environment:
  - name: SHIPLOGIC_API_URL
    value: "https://api.shiplogic.com/v2/rates?provider_id=123"

secrets:
  - name: SHIPLOGIC_API_KEY

auth:
  redirectUrl: http://localhost:3000/callback
  providers:
    - type: google
      name: google_client
      clientId: 197248210825-lmlmjjo4hkvaqslk79colj1c15l001mu.apps.googleusercontent.com